CREATE TABLE lista_vdb(
   NÚMERO       INTEGER  NOT NULL PRIMARY KEY 
  ,NOME         VARCHAR(31) NOT NULL
  ,CIDADE       VARCHAR(18) NOT NULL
  ,GRUPO        VARCHAR(16)
  ,TAM_CAMISETA VARCHAR(11)
  ,FONE         VARCHAR(14)
  ,RGCPF        VARCHAR(11)
  ,PAGO         VARCHAR(3)
);
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (639,'EVERTON LEDO DA ROCHA','ALTAMIRA DO PARANA',NULL,NULL,NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (333,'GILBERTO BUTI','ALTONIA','MTB ALTONIA','3G','999854299','44280965','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (513,'REGINALDO VIGO PAGANINI','ALTONIA',NULL,'G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (565,'WAGNER SILVANO DA SILVA','ALTONIA','FOCA ANIMAL','M',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (588,'EDERSON QUINTANA AMORIM','ALTONIA',NULL,'G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (589,'POLIANA REGINA DA SILVA AMORIM','ALTONIA',NULL,'M',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (24,'JONATAS FERREIRA DO SIQUEIRA','CAMPINAS-SP','NATIVOS XCO','M','19,989,667,940','503236457','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (503,'MANOEL PEREIRA DOS SANTOS','CURITIBA',NULL,'G',NULL,NULL,NULL);
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (422,'EVERTON R. SILVA','FORMOSA DO OESTE','PEDAL CROSS','G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (423,'RICARDO O. SILVA','FORMOSA DO OESTE','PEDAL CROSS','M',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (477,'MAIRON M. REIS','FORMOSA DO OESTE','PEDAL CROSS','GG',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (478,'ITHIENE B. PEREZ','FORMOSA DO OESTE','PEDAL CROSS','PP',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (534,'ANDERSON CARLOS SOARES NOGUEIRA','FORMOSA DO OESTE','PEDAL CROSS','G','4491378021','3534934903','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (529,'ANTONIO CARLOS FIGUEIRA','FOZ DO IGUACU',NULL,'M','4,599,282,637','50734145','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (488,'NELSON GOMES DA SILVA','GUAIRA',NULL,'GG',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (489,'ROSANGELA NERIS DA SILVA','GUAIRA',NULL,'G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (490,'GUILHERME NERIS DA SILVA','GUAIRA',NULL,'G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (491,'GUSTAVA NERIS DA SILVA','GUAIRA',NULL,'GG',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (572,'FELYPE MARTINS DE SOUZA','GUARAPUAVA',NULL,'G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (230,'REINALDO RODRIGUES BARBOSA','ICARAIMA','ICARAIMA MTB','3G','44,984,238,642','52100119','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (231,'IRACEMA MIDORI H. BARBOSA','ICARAIMA','ICARAIMA MTB','M','44,998,275,072','65244284','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (501,'JONATAS PERES DA SILVA','INDIANAPOLIS',NULL,'M',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (502,'GABRIEL GENTLIN','INDIANAPOLIS',NULL,'P',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (331,'VEDEVAL S BUTI','IPORA','MTB IPORA','3G','999277784','30195094','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (607,'JOAZITO OLIVEIRA DA SILVA','IVAIPORA','PEDAL IVAIPORA','S/ CAMISETA','043 99533567','37267701510','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (608,'WAGNER JOSE BONFIM','IVAIPORA','PEDAL IVAIPORA','S/ CAMISETA','043 99533567','2074902956','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (609,'MARCIA KAUANO BONFIM','IVAIPORA','PEDAL IVAIPORA','S/ CAMISETA','043 99533567','2017593907','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (393,'MARCELO DOS SANTOS CARNEIRO','JANIOPOLIS',NULL,'3G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (493,'VANESSA FABIANA FERREIRA','JANIOPOLIS',NULL,'P',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (509,'ALESSANDRO LINDNER','JANIOPOLIS',NULL,'GG',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (648,'CINTIA NERY GONCALVES SANTOS','JANIOPOLIS',NULL,NULL,NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (649,'ELTON ADRIANO DOS SANTOS','JANIOPOLIS',NULL,NULL,NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (637,'RAQUEL MOLINA DIAS','JESUITAS','PEDAL NA ESTRADA',NULL,NULL,'127088888','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (638,'MARCELO CAMPANERUTTI','JESUITAS','PEDAL NA ESTRADA',NULL,NULL,'101111792','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (216,'EDGAR UESU','JUSSARA',NULL,'G','984048770',NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (218,'EMERSON UESU','JUSSARA',NULL,'M','984048770',NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (605,'LUIZ ANTONIO SANTONI','LUIZIANA',NULL,'S/ CAMISETA',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (132,'ERITON AVANCINI','MARIALVA',NULL,'3G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (133,'ROSILENE ZULIN AVANCINI','MARIALVA',NULL,'M',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (206,'MARIANE ZULIN AVANCINI','MARIALVA',NULL,'G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (599,'ALESSANDRO GALEGO VILARINHO','MARIALVA',NULL,'M',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (600,'GERSON EGIDIO DOS SANTOS','MARIALVA',NULL,'3G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (220,'MICHELLE SCHWAAB','MATELANDIA','PEDAL DO BATOM','P','4,599,282,637','50313689','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (226,'DOUGLAS DANIEL','MEDIANEIRA','PEDAL MANGUACA','GG',NULL,NULL,NULL);
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (238,'ANDRE LUIZ WERNER MOTTER','MEDIANEIRA','PEDAL MANGUACA','3G','4,599,973,650','3353415947','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (219,'ISABETE SCHULTZ','PALOTINA','MTB PALOTINA','P',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (242,'ARIANE CHIMINELLI SGARBI','PALOTINA',NULL,'P','4,498,280,273','8023073966','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (243,'FABIELE CARLA MENTZ','PALOTINA',NULL,'P','4,498,280,273','5133140916','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (431,'LUIZ ILDEFONSO TELLES FILHO','PARAISO DO NORTE',NULL,'G',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (432,'CARLOS ALBERTO VIZZOTTO','PARAISO DO NORTE',NULL,'GG',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (414,'SELMA F. DA SILVA KOZIELSKI','QUINTA DO SOL','QUINTA DO SOL','G','4,484,099,152','7088795049','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (415,'IVO KOZIELSKI','QUINTA DO SOL','QUINTA DO SOL','GG','4,484,099,152','57186480934','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (301,'RODOLFO LUIS DOS SANTOS','TAPEJARA','COYOTES DO PEDAL','G','999778751','469682255','SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (504,'GABRIEL MOVAES BERNANDES','TAPEJARA',NULL,'M',NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (630,'WICTOR HUGO DA SILVA','TAPEJARA','COYOTES DO PEDAL',NULL,NULL,NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (631,'MAYCON JERONIMO PEREIRA','TAPEJARA',NULL,NULL,'998834604',NULL,'SIM');
INSERT INTO lista_vdb(NÚMERO,NOME,CIDADE,GRUPO,TAM_CAMISETA,FONE,RGCPF,PAGO) VALUES (632,'FABRICIO ALVES','TAPEJARA','COYOTES DO PEDAL',NULL,'998815071',NULL,'SIM');
